### PR TITLE
Update bot.js

### PR DESCRIPTION
**Pull request by KeyboardWalking**
fixed

### CODE REVIEW

**Comment by lemtzas** [comment]
LOL
image

I'll drop the ping/pong, though.

**Comment by KeyboardWalking** [comment]
Hey man! I was wondering if there was anyway to use your bot, but add one
thing.. I m looking for it to so everything it does but also has a way to
program X command to say X phrase on chat when you say the command. ?

**Comment by KeyboardWalking** [comment]
And also havs only the channel owner be able to trigger the phrase command

**Comment by lemtzas** [comment]
I'm not sure what a channel owner is.

An echo-style command is pretty easy to make, but what's the use case?

**Comment by KeyboardWalking** [comment]
channel owner, the admin. and im just trying to add it to rollbot

**Comment by KeyboardWalking** [comment]
hey ill give you some bitcoin if you can help me out with this bot man.

**Pull request closed without merging**
